name: Test Forge

on:
    pull_request:
      paths:
      - 'kgforge/**'
      - '.github/workflows/test.yml'
    push:
      branches:
        - master
jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install .[dev]
      - name: Lint pycodestyle the code
        run:  tox -e lint
      - name: Run tests with pytest
        run: 
          pytest tests/
      
